apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  labels:
    nodetype: spot
  name: nodepool-64g-spot-d-202309290
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  # limits:
  #   cpu: "32"
  template:
    spec:
      nodeClassRef:
        name: node-64g-202309290
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.azure.com/sku-family
        operator: In
        values:
        - D
      taints:
      - effect: NoSchedule
        key: spot
        value: "true"